name: u1_oscar_norman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/portrait.png
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600


